// Package convert holds generic converters that operate on already-decoded
// objects (the result of json.Unmarshal / yaml.Unmarshal). It only depends on
// the standard library so it can be reused by the json, yaml and csv packages
// without creating an import cycle.
package convert

import (
	"bytes"
	"encoding/csv"
	"fmt"
	"math"
	"sort"
	"strings"
	"unicode"
)

// ObjectToXML renders a decoded object as an indented XML document wrapped in a
// single <root> element. Maps become nested elements, slices repeat their tag.
func ObjectToXML(obj interface{}) string {
	var b strings.Builder
	b.WriteString("<root>\n")
	switch val := obj.(type) {
	case map[string]interface{}:
		for _, k := range sortedKeys(val) {
			writeElement(&b, k, val[k], 1)
		}
	case []interface{}:
		for _, item := range val {
			writeElement(&b, "item", item, 1)
		}
	default:
		b.WriteString(indent(1) + escapeXML(scalar(obj)) + "\n")
	}
	b.WriteString("</root>")
	return b.String()
}

func writeElement(b *strings.Builder, name string, v interface{}, depth int) {
	ind := indent(depth)
	switch val := v.(type) {
	case map[string]interface{}:
		b.WriteString(ind + "<" + name + ">\n")
		for _, k := range sortedKeys(val) {
			writeElement(b, k, val[k], depth+1)
		}
		b.WriteString(ind + "</" + name + ">\n")
	case []interface{}:
		for _, item := range val {
			writeElement(b, name, item, depth)
		}
	case nil:
		b.WriteString(ind + "<" + name + "></" + name + ">\n")
	default:
		b.WriteString(ind + "<" + name + ">" + escapeXML(scalar(val)) + "</" + name + ">\n")
	}
}

// ObjectToDelimited renders a decoded object as delimiter-separated values
// (CSV when comma is ',', TSV when it is '\t'). The object is expected to be an
// array of objects or a single object; columns are the sorted union of keys.
func ObjectToDelimited(obj interface{}, comma rune) (string, error) {
	rows := toRows(obj)
	cols := unionKeys(rows)

	var buf bytes.Buffer
	w := csv.NewWriter(&buf)
	w.Comma = comma
	if err := w.Write(cols); err != nil {
		return "", err
	}
	for _, row := range rows {
		rec := make([]string, len(cols))
		for i, c := range cols {
			if v, ok := row[c]; ok && v != nil {
				rec[i] = scalar(v)
			}
		}
		if err := w.Write(rec); err != nil {
			return "", err
		}
	}
	w.Flush()
	if err := w.Error(); err != nil {
		return "", err
	}
	return strings.TrimRight(buf.String(), "\n"), nil
}

// ObjectToGoStruct generates a Go type definition matching the shape of a
// decoded JSON/YAML object.
func ObjectToGoStruct(obj interface{}) string {
	var b strings.Builder
	b.WriteString("type AutoGenerated ")
	writeGoType(&b, obj, 0)
	b.WriteString("\n")
	return b.String()
}

func writeGoType(b *strings.Builder, v interface{}, depth int) {
	switch val := v.(type) {
	case map[string]interface{}:
		b.WriteString("struct {\n")
		for _, k := range sortedKeys(val) {
			b.WriteString(indent(depth+1) + exportName(k) + " ")
			writeGoType(b, val[k], depth+1)
			b.WriteString(fmt.Sprintf(" `json:%q`\n", k))
		}
		b.WriteString(indent(depth) + "}")
	case []interface{}:
		b.WriteString("[]")
		if len(val) == 0 {
			b.WriteString("interface{}")
		} else {
			writeGoType(b, val[0], depth)
		}
	case bool:
		b.WriteString("bool")
	case float64:
		if val == math.Trunc(val) && !math.IsInf(val, 0) {
			b.WriteString("int")
		} else {
			b.WriteString("float64")
		}
	case string:
		b.WriteString("string")
	case nil:
		b.WriteString("interface{}")
	default:
		b.WriteString("interface{}")
	}
}

func toRows(obj interface{}) []map[string]interface{} {
	switch val := obj.(type) {
	case []interface{}:
		rows := make([]map[string]interface{}, 0, len(val))
		for _, item := range val {
			if m, ok := item.(map[string]interface{}); ok {
				rows = append(rows, m)
			}
		}
		return rows
	case map[string]interface{}:
		return []map[string]interface{}{val}
	}
	return nil
}

func unionKeys(rows []map[string]interface{}) []string {
	set := map[string]struct{}{}
	for _, r := range rows {
		for k := range r {
			set[k] = struct{}{}
		}
	}
	cols := make([]string, 0, len(set))
	for k := range set {
		cols = append(cols, k)
	}
	sort.Strings(cols)
	return cols
}

func sortedKeys(m map[string]interface{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func scalar(v interface{}) string {
	return fmt.Sprintf("%v", v)
}

func indent(depth int) string {
	return strings.Repeat("    ", depth)
}

var xmlEscaper = strings.NewReplacer(
	"&", "&amp;",
	"<", "&lt;",
	">", "&gt;",
	"\"", "&quot;",
	"'", "&apos;",
)

func escapeXML(in string) string {
	return xmlEscaper.Replace(in)
}

// exportName turns an arbitrary object key into an exported Go field name, e.g.
// "first_name" -> "FirstName", "user-id" -> "UserId".
func exportName(key string) string {
	var b strings.Builder
	upperNext := true
	for _, r := range key {
		switch {
		case r == '_' || r == '-' || r == ' ' || r == '.':
			upperNext = true
		case upperNext:
			b.WriteRune(unicode.ToUpper(r))
			upperNext = false
		default:
			b.WriteRune(r)
		}
	}
	name := b.String()
	if name == "" {
		return "Field"
	}
	if r := rune(name[0]); unicode.IsDigit(r) {
		return "Field" + name
	}
	return name
}
