package convert

import (
	"encoding/json"
	"testing"
)

func decode(t *testing.T, in string) interface{} {
	t.Helper()
	var obj interface{}
	if err := json.Unmarshal([]byte(in), &obj); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	return obj
}

func TestObjectToXML(t *testing.T) {
	got := ObjectToXML(decode(t, `{"name":"ada","tags":["a","b"]}`))
	want := "<root>\n    <name>ada</name>\n    <tags>a</tags>\n    <tags>b</tags>\n</root>"
	if got != want {
		t.Errorf("ObjectToXML\n got: %q\nwant: %q", got, want)
	}
}

func TestObjectToXMLEscaping(t *testing.T) {
	got := ObjectToXML(decode(t, `{"k":"a & b < c"}`))
	want := "<root>\n    <k>a &amp; b &lt; c</k>\n</root>"
	if got != want {
		t.Errorf("got %q want %q", got, want)
	}
}

func TestObjectToDelimitedCSV(t *testing.T) {
	got, err := ObjectToDelimited(decode(t, `[{"name":"ada","age":36},{"name":"bob","city":"NYC"}]`), ',')
	if err != nil {
		t.Fatal(err)
	}
	want := "age,city,name\n36,,ada\n,NYC,bob"
	if got != want {
		t.Errorf("CSV\n got: %q\nwant: %q", got, want)
	}
}

func TestObjectToDelimitedQuoting(t *testing.T) {
	got, err := ObjectToDelimited(decode(t, `[{"v":"x,y"}]`), ',')
	if err != nil {
		t.Fatal(err)
	}
	want := "v\n\"x,y\""
	if got != want {
		t.Errorf("got %q want %q", got, want)
	}
}

func TestObjectToDelimitedTSV(t *testing.T) {
	got, err := ObjectToDelimited(decode(t, `[{"a":1,"b":2}]`), '\t')
	if err != nil {
		t.Fatal(err)
	}
	want := "a\tb\n1\t2"
	if got != want {
		t.Errorf("got %q want %q", got, want)
	}
}

func TestObjectToGoStruct(t *testing.T) {
	got := ObjectToGoStruct(decode(t, `{"first_name":"ada","age":36,"score":1.5,"ok":true,"tags":["x"]}`))
	want := "type AutoGenerated struct {\n" +
		"    Age int `json:\"age\"`\n" +
		"    FirstName string `json:\"first_name\"`\n" +
		"    Ok bool `json:\"ok\"`\n" +
		"    Score float64 `json:\"score\"`\n" +
		"    Tags []string `json:\"tags\"`\n" +
		"}\n"
	if got != want {
		t.Errorf("GoStruct\n got: %q\nwant: %q", got, want)
	}
}

func TestExportName(t *testing.T) {
	cases := map[string]string{
		"first_name": "FirstName",
		"user-id":    "UserId",
		"city":       "City",
		"2cool":      "Field2cool",
		"":           "Field",
	}
	for in, want := range cases {
		if got := exportName(in); got != want {
			t.Errorf("exportName(%q) = %q, want %q", in, got, want)
		}
	}
}
