package json

import "testing"

func TestToXML(t *testing.T) {
	got, err := ToXML(`{"name":"ada"}`)
	if err != nil {
		t.Fatal(err)
	}
	want := "<root>\n    <name>ada</name>\n</root>"
	if got != want {
		t.Errorf("got %q want %q", got, want)
	}
}

func TestToCSV(t *testing.T) {
	got, err := ToCSV(`[{"a":1,"b":2}]`)
	if err != nil {
		t.Fatal(err)
	}
	if got != "a,b\n1,2" {
		t.Errorf("got %q", got)
	}
}

func TestToTSV(t *testing.T) {
	got, err := ToTSV(`[{"a":1,"b":2}]`)
	if err != nil {
		t.Fatal(err)
	}
	if got != "a\tb\n1\t2" {
		t.Errorf("got %q", got)
	}
}

func TestEscapeUnescapeRoundTrip(t *testing.T) {
	raw := "He said \"hi\"\nbye\tend"
	escaped, err := Escape(raw)
	if err != nil {
		t.Fatal(err)
	}
	if escaped != `He said \"hi\"\nbye\tend` {
		t.Errorf("escape got %q", escaped)
	}
	back, err := Unescape(escaped)
	if err != nil {
		t.Fatal(err)
	}
	if back != raw {
		t.Errorf("round trip got %q want %q", back, raw)
	}
}

func TestUnescapeWithQuotes(t *testing.T) {
	got, err := Unescape(`"a\tb"`)
	if err != nil {
		t.Fatal(err)
	}
	if got != "a\tb" {
		t.Errorf("got %q", got)
	}
}

func TestToGoStruct(t *testing.T) {
	got, err := ToGoStruct(`{"id":1}`)
	if err != nil {
		t.Fatal(err)
	}
	want := "type AutoGenerated struct {\n    Id int `json:\"id\"`\n}\n"
	if got != want {
		t.Errorf("got %q want %q", got, want)
	}
}

func TestToXMLInvalid(t *testing.T) {
	if _, err := ToXML(`{not json`); err == nil {
		t.Error("expected error for invalid json")
	}
}
